fix(main): add anyhow context when parsing private key env var
When misconfiguring the environment variable the error message printed
was just telling the user that parsing a felt has failed:

```
13:17:57.047655Z  INFO starknet_validator_attestation: Using local signer
Error: Failed to create Felt from string
```

This commit adds a context to the error message, so that the user
can see that the error is related to the private key environment variable:

```
2025-04-29T13:40:34.961888Z  INFO starknet_validator_attestation: Using local signer
Error: Parsing private key

Caused by:
    Failed to create Felt from string
```